
import java.text.DecimalFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author el51909
 */
public class computerConfiguratorAssignment extends javax.swing.JFrame {

    /**
     * Creates new form computerConfiguratorAssignment
     */
    public computerConfiguratorAssignment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbBaseProcessor = new javax.swing.JRadioButton();
        rbOneHund = new javax.swing.JRadioButton();
        rbTwoHund = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbFourGB = new javax.swing.JRadioButton();
        rbEightGB = new javax.swing.JRadioButton();
        rbSixteenGB = new javax.swing.JRadioButton();
        rbThirtytwoGB = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbTwoFiftyGB = new javax.swing.JRadioButton();
        rbFiveHundGB = new javax.swing.JRadioButton();
        rbOneTB = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        cbOfficePkg = new javax.swing.JCheckBox();
        cbAcctPkg = new javax.swing.JCheckBox();
        cbGraphicsPkg = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        rbWinHomeEd = new javax.swing.JRadioButton();
        rbWinProEd = new javax.swing.JRadioButton();
        btnReset = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnCalc = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Computer Configurator");
        setLocation(new java.awt.Point(600, 300));
        setName("compConfig"); // NOI18N

        jLabel1.setText("Computer base price: $500.00");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setText("Choose a Processor:");

        buttonGroup1.add(rbBaseProcessor);
        rbBaseProcessor.setSelected(true);
        rbBaseProcessor.setText("Intel 3.2GHz included in base price");

        buttonGroup1.add(rbOneHund);
        rbOneHund.setText("Intel 3.6GHz add $100.00 ");

        buttonGroup1.add(rbTwoHund);
        rbTwoHund.setText("Intel 4.0GHz add $200.00");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setText("Choose a Memory Config:");

        buttonGroup2.add(rbFourGB);
        rbFourGB.setSelected(true);
        rbFourGB.setText("4GB included in base price");

        buttonGroup2.add(rbEightGB);
        rbEightGB.setText("8GB add $50.00");

        buttonGroup2.add(rbSixteenGB);
        rbSixteenGB.setText("16GB add $100.00");

        buttonGroup2.add(rbThirtytwoGB);
        rbThirtytwoGB.setText("32GB add $200.00");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setText("Choose a Disk Config:");

        buttonGroup4.add(rbTwoFiftyGB);
        rbTwoFiftyGB.setSelected(true);
        rbTwoFiftyGB.setText("250GB included in base price");

        buttonGroup4.add(rbFiveHundGB);
        rbFiveHundGB.setText("500GB add $100.00");

        buttonGroup4.add(rbOneTB);
        rbOneTB.setText("1TB add $150.00");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setText("Choose any of these Packages:");

        cbOfficePkg.setText("Office package add $400.00");

        cbAcctPkg.setText("Accounting package add $200.00");

        cbGraphicsPkg.setText("Graphics software package add $600.00");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setText("Choose an Operating System:");

        buttonGroup3.add(rbWinHomeEd);
        rbWinHomeEd.setSelected(true);
        rbWinHomeEd.setText("Windows 10 Home Edition included in base price");

        buttonGroup3.add(rbWinProEd);
        rbWinProEd.setText("Windows 10 Professional add $100.00");

        btnReset.setText("Reset");
        btnReset.setPreferredSize(new java.awt.Dimension(85, 25));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Total:");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lblTotal.setPreferredSize(new java.awt.Dimension(80, 25));

        btnCalc.setText("Calculate");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.setPreferredSize(new java.awt.Dimension(85, 25));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(btnCalc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(rbWinHomeEd)
                            .addComponent(rbThirtytwoGB)
                            .addComponent(jLabel1)
                            .addComponent(rbWinProEd)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(rbBaseProcessor)
                                    .addComponent(rbOneHund)
                                    .addComponent(rbTwoHund)
                                    .addComponent(jLabel3)
                                    .addComponent(rbFourGB)
                                    .addComponent(rbEightGB)
                                    .addComponent(rbSixteenGB))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbGraphicsPkg)
                                    .addComponent(cbAcctPkg)
                                    .addComponent(cbOfficePkg)
                                    .addComponent(jLabel5)
                                    .addComponent(rbOneTB)
                                    .addComponent(rbFiveHundGB)
                                    .addComponent(rbTwoFiftyGB)
                                    .addComponent(jLabel4))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBaseProcessor)
                    .addComponent(rbTwoFiftyGB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOneHund)
                    .addComponent(rbFiveHundGB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbTwoHund)
                    .addComponent(rbOneTB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFourGB)
                    .addComponent(cbOfficePkg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEightGB)
                    .addComponent(cbAcctPkg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSixteenGB)
                    .addComponent(cbGraphicsPkg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbThirtytwoGB)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbWinHomeEd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbWinProEd)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalc)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        ResetPrice();
        this.rbBaseProcessor.setSelected(true);
        this.rbFourGB.setSelected(true);
        this.rbWinHomeEd.setSelected(true);
        this.rbTwoFiftyGB.setSelected(true);
        this.cbAcctPkg.setSelected(false);
        this.cbGraphicsPkg.setSelected(false);
        this.cbOfficePkg.setSelected(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        ResetPrice();
        
        DecimalFormat df = new DecimalFormat("0.00");
        this.lblTotal.setText("$" + df.format(getPackages() + getProcessor() + getMemory() + getOP() + getDiskConfig() + 500));
    }//GEN-LAST:event_btnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    private void ResetPrice(){
        this.lblTotal.setText("");
    }
    private double getProcessor(){
        double price = 0;
        if(this.rbBaseProcessor.isSelected()){
            price = 0;
        }else if(this.rbOneHund.isSelected()){
            price = 100;
        }else if(this.rbTwoHund.isSelected()){
            price = 200;
        }
        return price;
    }
    
    private double getMemory(){
        double price = 0;
        if(this.rbFourGB.isSelected()){
            price = 0;
        }else if(this.rbEightGB.isSelected()){
            price = 50;
        }else if(this.rbSixteenGB.isSelected()){
            price = 100;
        }else if(this.rbThirtytwoGB.isSelected()){
            price = 200;
        }
        return price;
    }
    
    private double getDiskConfig(){
        double price = 0;
        if(this.rbTwoFiftyGB.isSelected()){
            price = 0;
        }else if(this.rbFiveHundGB.isSelected()){
            price = 100;
        }else if(this.rbOneTB.isSelected()){
            price = 150;
        }
        return price;
    }
    
    private double getOP(){
        double price = 0;
        if(this.rbWinHomeEd.isSelected()){
            price = 0;
        }else if(this.rbWinProEd.isSelected()){
            price = 100;
        }
        return price;
    }
    
    private double getPackages(){
        double price = 0;
        if(this.cbOfficePkg.isSelected()){
            price += 400;
        }
        if(this.cbAcctPkg.isSelected()){
            price += 200;
        }
        if(this.cbGraphicsPkg.isSelected()){
            price += 600;
        }
        return price;
    }
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(computerConfiguratorAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(computerConfiguratorAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(computerConfiguratorAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(computerConfiguratorAssignment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new computerConfiguratorAssignment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox cbAcctPkg;
    private javax.swing.JCheckBox cbGraphicsPkg;
    private javax.swing.JCheckBox cbOfficePkg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rbBaseProcessor;
    private javax.swing.JRadioButton rbEightGB;
    private javax.swing.JRadioButton rbFiveHundGB;
    private javax.swing.JRadioButton rbFourGB;
    private javax.swing.JRadioButton rbOneHund;
    private javax.swing.JRadioButton rbOneTB;
    private javax.swing.JRadioButton rbSixteenGB;
    private javax.swing.JRadioButton rbThirtytwoGB;
    private javax.swing.JRadioButton rbTwoFiftyGB;
    private javax.swing.JRadioButton rbTwoHund;
    private javax.swing.JRadioButton rbWinHomeEd;
    private javax.swing.JRadioButton rbWinProEd;
    // End of variables declaration//GEN-END:variables
}
