/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author el51909
 */
public class frmAddress extends javax.swing.JFrame {

    /**
     * Creates new form frmAddress
     */
    public frmAddress() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        nameOutput = new javax.swing.JLabel();
        addOutput = new javax.swing.JLabel();
        lblAdd = new javax.swing.JLabel();
        cityStateOutput = new javax.swing.JLabel();
        lblCityState = new javax.swing.JLabel();
        movieOutput = new javax.swing.JLabel();
        lblMovie = new javax.swing.JLabel();
        foodOutput = new javax.swing.JLabel();
        lblFood = new javax.swing.JLabel();
        colorOutput = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("About Me");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setLocation(new java.awt.Point(500, 313));
        setName("About Me"); // NOI18N

        lblName.setFont(new java.awt.Font("Segoe UI Light", 3, 13)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name:");

        nameOutput.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        nameOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        addOutput.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        addOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAdd.setFont(new java.awt.Font("Segoe UI Light", 3, 13)); // NOI18N
        lblAdd.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblAdd.setText("Address:");

        cityStateOutput.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        cityStateOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cityStateOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCityState.setFont(new java.awt.Font("Segoe UI Light", 3, 13)); // NOI18N
        lblCityState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCityState.setText("City, State:");

        movieOutput.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        movieOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movieOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMovie.setFont(new java.awt.Font("Segoe UI Light", 3, 13)); // NOI18N
        lblMovie.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMovie.setText("Movie:");

        foodOutput.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        foodOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        foodOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFood.setFont(new java.awt.Font("Segoe UI Light", 3, 13)); // NOI18N
        lblFood.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFood.setText("Food:");

        colorOutput.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        colorOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colorOutput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblColor.setFont(new java.awt.Font("Segoe UI Light", 3, 13)); // NOI18N
        lblColor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblColor.setText("Color:");

        btnAdd.setBackground(new java.awt.Color(0, 204, 204));
        btnAdd.setText("Address");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnInfo.setBackground(new java.awt.Color(0, 204, 204));
        btnInfo.setText("Info");
        btnInfo.setMaximumSize(new java.awt.Dimension(79, 25));
        btnInfo.setMinimumSize(new java.awt.Dimension(79, 25));
        btnInfo.setPreferredSize(new java.awt.Dimension(79, 25));
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 0, 0));
        btnReset.setText("Reset");
        btnReset.setMaximumSize(new java.awt.Dimension(79, 25));
        btnReset.setMinimumSize(new java.awt.Dimension(79, 25));
        btnReset.setPreferredSize(new java.awt.Dimension(79, 25));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nameOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblCityState, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cityStateOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFood, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(foodOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(colorOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(movieOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFood, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(foodOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movieOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCityState, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityStateOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(btnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        lblName.getAccessibleContext().setAccessibleName("lblName");
        nameOutput.getAccessibleContext().setAccessibleName("nameOutput");
        addOutput.getAccessibleContext().setAccessibleName("addOutput");
        lblAdd.getAccessibleContext().setAccessibleName("lblAddress");
        cityStateOutput.getAccessibleContext().setAccessibleName("cityStateOutput");
        lblCityState.getAccessibleContext().setAccessibleName("lblCityState");
        movieOutput.getAccessibleContext().setAccessibleName("movieOutput");
        lblMovie.getAccessibleContext().setAccessibleName("lblMovie");
        foodOutput.getAccessibleContext().setAccessibleName("foodOutput");
        lblFood.getAccessibleContext().setAccessibleName("lblFood");
        colorOutput.getAccessibleContext().setAccessibleName("colorOutput");
        lblColor.getAccessibleContext().setAccessibleName("lblColor");
        btnAdd.getAccessibleContext().setAccessibleName("btnAdd");
        btnInfo.getAccessibleContext().setAccessibleName("btnInfo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        this.nameOutput.setText("Erik Lee");
        this.addOutput.setText("220 5th Ave SW");
        this.cityStateOutput.setText("Watertown, SD");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        this.foodOutput.setText("Pizza");
        this.colorOutput.setText("Green");
        this.movieOutput.setText("A Christmas Carol");
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        this.nameOutput.setText("");
        this.addOutput.setText("");
        this.cityStateOutput.setText("");
        this.colorOutput.setText("");
        this.foodOutput.setText("");
        this.movieOutput.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAddress().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addOutput;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel cityStateOutput;
    private javax.swing.JLabel colorOutput;
    private javax.swing.JLabel foodOutput;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblCityState;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblMovie;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel movieOutput;
    private javax.swing.JLabel nameOutput;
    // End of variables declaration//GEN-END:variables
}
